### ISSUE TITLE
Main/side quest Shulker kill issue.

### ISSUE THREAD

**Issue by ATT2CHTranslationTeam** [Piccomaster/AcrossTheTime2#77]
I have received feedback from players:

Players can click on certain side/main quest prompts to spawn an unlimited number of Shulkers, then kill them to gain a lot of experience... a massive amount of experience. I think it's necessary to impose some restrictions.

Mainly because the prompts in the chat box can be clicked infinitely, and there's no limit to the number of Shulkers that can be spawned...

**Comment by Piccomaster** [comment]
Shulkers are not supposed to spawn in the air but underground normally. This should indeed be corrected by changing the system so that they are invulnerable but otherwise die mechanically, hmm I don't know we have to think about it.

**Comment by orian34** [comment]
Should be doable, making the shulkers invulnerable, and using a special value effect, and when it runs out, on a 1-2 second clock you kill shulkers with the tag that don't have the effect. (Sending to the void first to avoid weird animation when it dies, and potential xp shenanigans)

**Comment by ATT2CHTranslationTeam** [comment]
I added a command to kill the previous Shulker before generating a new one. While this doesn't solve the issue of farming experience, it does prevent the lag caused by an excessive number of entities due to too many Shulkers being spawned.
